# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "juice"

output_dir = "docs"

# The URL the site will be built for
base_url = "/"

title = "Jala Marwita Lestari - An Indonesia-based foundation to advance knowledge in the fields of computer science and informatics."
# default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Configuration of the Markdown rendering
[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "kronuz"

[extra]
juice_logo_name = "Jala Marwita Lestari"
juice_logo_path = "logo.png"
juice_extra_menu = [
    { title = "Github", link = "https://github.com/jalamarwitalestari" }
]
# Add page titles here to exclude them from the nav section (case sensitive)
juice_exclude_menu = [
    "exclude_from_nav"
]
repository_url = "https://github.com/jalamarwitalestari"

